title: Elliot's Blog
description: > # this means to ignore newlines until "baseurl:"
  Life is 10% what happens to you and 90% how you react to it.
permalink: ":title/"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ellialder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
google_analytics: UA-126736504-1
# Author Settings
author: Elliot Alderson # add your name
author-img: elliot-alderson.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: ellialdero # add your Twitter handle
social-facebook: ellialdero # add your Facebook handle
social-github: ellialdero # add your Github handle
social-linkedin: ellialdero # add your Linkedin handle
social-email: ellialdero9@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
